/* src/config.h.  Dummy version -- will be overwritten by 
                  the version generated by configure.  */

/* Define these first for testing purposes */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "matthew.whiting@csiro.au"

/* Define to the full name of this package. */
#define PACKAGE_NAME "Duchamp"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "Duchamp 1.1.7"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "duchamp"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.1.7"

/* Define to 1 if stdbool.h conforms to C99. */
#define HAVE_STDBOOL_H 1

/* Define this to utilise the testing parts of the code -- bits that
   won't normally be utilised */
#define TEST_DEBUG

/* Assume we have PGPLOT working for testing purposes... */
#define HAVE_PGPLOT 1
